spring:
  data:
    redis:
      url: redis://default:8RzfG5vYnmyz1whV8szTjI3aKIzf9bGF@redis-15906.c302.asia-northeast1-1.gce.redns.redis-cloud.com:15906
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Daika1999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  web:
    resources:
      static-locations: file:./product-images/,classpath:/static/
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8081
    address: 127.0.0.1
server:
  servlet:
    encoding:
      charset: utf-8
      force: true

object-storage:
  endpoint: s3.cloudfly.vn
  accessKey: Y6YD1DPIFL02O3LTNMFI
  secretKey: txmXGuB8tUixjP82DS0qIg2JqNoyNV6vWFvwSrFV
  bucketName: anlv

pre-api: /api/v1

