spring:
  data:
    redis:
      url: redis://default:8RzfG5vYnmyz1whV8szTjI3aKIzf9bGF@redis-15906.c302.asia-northeast1-1.gce.redns.redis-cloud.com:15906
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Daika1999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60 # a day
      refresh-token:
        expiration: 604800000 # 7 days
management:
  server:
    port: 8081
    address: 127.0.0.1

